apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vue-demo
  name: dep-vue-demo
spec:
  selector:
    matchLabels:
      app: vue-demo
  template:
    metadata:
      labels:
        app: vue-demo
    spec:
      containers:
        - image: '192.168.17.1:60080/devops/vue-demo'
          name: vue-demo
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 80
